import React, { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { ArrowLeft, Download, FileText, FileSpreadsheet } from 'lucide-react'
import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import { Layout } from '../components/layout/Layout'
import { Card, CardContent } from '../components/ui/Card'
import { Button } from '../components/ui/Button'
import { useBudgetStore } from '../store/budgetStore'
import { useToast } from '../hooks/useToast'
import { downloadCSV, getMonthName, formatFullCurrency } from '../lib/utils'

export const Export: React.FC = () => {
  const navigate = useNavigate()
  const { entries, selectedMonth, selectedYear, getOverview } = useBudgetStore()
  const { showSuccess, showError } = useToast()
  const [isExporting, setIsExporting] = useState<'csv' | 'pdf' | null>(null)

  const handleExportCSV = () => {
    setIsExporting('csv')

    try {
      const data = entries.map(entry => ({
        Category: entry.category.charAt(0).toUpperCase() + entry.category.slice(1),
        Name: entry.name,
        Planned: entry.planned,
        Actual: entry.actual,
        Percentage: entry.planned > 0 ? `${Math.round((entry.actual / entry.planned) * 100)}%` : '0%',
      }))

      downloadCSV(data, `budget-${selectedMonth}-${selectedYear}`)
      showSuccess('CSV exported successfully')
    } catch {
      showError('Failed to export CSV')
    } finally {
      setIsExporting(null)
    }
  }

  const handleExportPDF = () => {
    setIsExporting('pdf')

    try {
      const doc = new jsPDF()
      const overview = getOverview()
      const monthName = getMonthName(selectedMonth)

      // Title
      doc.setFontSize(20)
      doc.setTextColor(79, 124, 255)
      doc.text('Finance Planner Report', 105, 20, { align: 'center' })

      // Subtitle
      doc.setFontSize(14)
      doc.setTextColor(100)
      doc.text(`${monthName} ${selectedYear}`, 105, 30, { align: 'center' })

      // Summary Section
      doc.setFontSize(12)
      doc.setTextColor(50)
      doc.text('Summary', 14, 45)

      const summaryData = [
        ['Category', 'Planned', 'Actual'],
        ['Income', formatFullCurrency(overview.income.planned), formatFullCurrency(overview.income.actual)],
        ['Expenses', formatFullCurrency(overview.expenses.planned), formatFullCurrency(overview.expenses.actual)],
        ['Bills', formatFullCurrency(overview.bills.planned), formatFullCurrency(overview.bills.actual)],
        ['Savings', formatFullCurrency(overview.savings.planned), formatFullCurrency(overview.savings.actual)],
        ['Debt', formatFullCurrency(overview.debt.planned), formatFullCurrency(overview.debt.actual)],
        ['Remaining', formatFullCurrency(overview.remaining.planned), formatFullCurrency(overview.remaining.actual)],
      ]

      autoTable(doc, {
        startY: 50,
        head: [summaryData[0]],
        body: summaryData.slice(1),
        theme: 'striped',
        headStyles: { fillColor: [79, 124, 255] },
        margin: { left: 14, right: 14 },
      })

      // Entries Section
      const finalY = (doc as typeof doc & { lastAutoTable?: { finalY?: number } }).lastAutoTable?.finalY || 100
      doc.text('Detailed Entries', 14, finalY + 15)

      const entriesData = entries.map(entry => [
        entry.category.charAt(0).toUpperCase() + entry.category.slice(1),
        entry.name,
        formatFullCurrency(entry.planned),
        formatFullCurrency(entry.actual),
        entry.planned > 0 ? `${Math.round((entry.actual / entry.planned) * 100)}%` : '0%',
      ])

      autoTable(doc, {
        startY: finalY + 20,
        head: [['Category', 'Name', 'Planned', 'Actual', '%']],
        body: entriesData,
        theme: 'striped',
        headStyles: { fillColor: [79, 124, 255] },
        margin: { left: 14, right: 14 },
      })

      // Footer
      const pageCount = doc.getNumberOfPages()
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i)
        doc.setFontSize(8)
        doc.setTextColor(150)
        doc.text(
          `Generated by Finance Planner • Page ${i} of ${pageCount}`,
          105,
          doc.internal.pageSize.height - 10,
          { align: 'center' }
        )
      }

      doc.save(`budget-${selectedMonth}-${selectedYear}.pdf`)
      showSuccess('PDF exported successfully')
    } catch {
      showError('Failed to export PDF')
    } finally {
      setIsExporting(null)
    }
  }

  return (
    <Layout>
      <div className="max-w-2xl mx-auto">
        {/* Header */}
        <div className="flex items-center gap-4 mb-6">
          <button
            onClick={() => navigate('/')}
            className="p-2 rounded-lg hover:bg-white transition-colors"
          >
            <ArrowLeft className="w-5 h-5 text-gray-600" />
          </button>
          <div>
            <h1 className="text-2xl font-bold text-gray-800">Export Data</h1>
            <p className="text-gray-500">Download your budget data</p>
          </div>
        </div>

        {/* Export Options */}
        <div className="space-y-4">
          <Card>
            <CardContent>
              <div className="flex items-start gap-4">
                <div className="p-4 rounded-xl bg-green-100">
                  <FileSpreadsheet className="w-8 h-8 text-green-600" />
                </div>
                <div className="flex-1">
                  <h3 className="text-lg font-semibold text-gray-800 mb-1">
                    Export as CSV
                  </h3>
                  <p className="text-sm text-gray-500 mb-4">
                    Download your budget data as a spreadsheet file. 
                    Compatible with Excel, Google Sheets, and other spreadsheet apps.
                  </p>
                  <Button
                    onClick={handleExportCSV}
                    isLoading={isExporting === 'csv'}
                    leftIcon={<Download className="w-4 h-4" />}
                  >
                    Download CSV
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>

          <Card>
            <CardContent>
              <div className="flex items-start gap-4">
                <div className="p-4 rounded-xl bg-red-100">
                  <FileText className="w-8 h-8 text-red-600" />
                </div>
                <div className="flex-1">
                  <h3 className="text-lg font-semibold text-gray-800 mb-1">
                    Export as PDF
                  </h3>
                  <p className="text-sm text-gray-500 mb-4">
                    Generate a formatted PDF report of your budget. 
                    Perfect for printing or sharing.
                  </p>
                  <Button
                    onClick={handleExportPDF}
                    isLoading={isExporting === 'pdf'}
                    leftIcon={<Download className="w-4 h-4" />}
                  >
                    Download PDF
                  </Button>
                </div>
              </div>
            </CardContent>
          </Card>

          {/* Current Period Info */}
          <Card className="bg-gray-50">
            <CardContent>
              <p className="text-sm text-gray-500 text-center">
                Exporting data for <span className="font-semibold text-gray-700">
                  {getMonthName(selectedMonth)} {selectedYear}
                </span>
                <br />
                <span className="text-gray-400">{entries.length} entries</span>
              </p>
            </CardContent>
          </Card>
        </div>
      </div>
    </Layout>
  )
}

